### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by andruwa13** [rancher/migration-tools#6]
./migration-tools_darwin-amd64 --docker-file=docker-compose.yml --rancher-file=rancher-compose.yml
INFO[2018-10-17T00:37:44+03:00] ---Starting migration helper tool---
FATA[2018-10-17T00:37:44+03:00] Failed parsing the compose files, error: Failed to parse the docker-compose yaml file, error: yaml: unmarshal errors:
  line 7: cannot unmarshal !!seq into map[string]interface {}
  line 48: cannot unmarshal !!seq into map[string]interface {}
  line 65: cannot unmarshal !!seq into map[string]interface {}
  line 76: cannot unmarshal !!seq into map[string]interface {}

**Comment by prachidamle** [comment]
@andruwa13 can you check if this is resolved with the latest release? Thanks!

**Comment by andruwa13** [comment]
@prachidamle Good work
